### ISSUE TITLE
"Error: data out-of-bounds (length=0, offset=32, version=abi/5.0.0-beta.138)

### ISSUE THREAD

**Issue by ligi** [blockchainsllc/in3-server#6]
happens with a node created with http://in3-setup.slock.it
```
incubed-server_1  | {"errStack":"Error: data out-of-bounds (length=0, offset=32, version=abi/5.0.0-beta.138)\n    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:105:21)\n    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:114:20)\n    at Reader._peekBytes (/app/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:112:20)\n    at Reader.readBytes (/app/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:123:26)\n    at Reader.readValue (/app/node_modules/@ethersproject/abi/lib/coders/abstract-coder.js:129:48)\n    at NumberCoder.decode (/app/node_modules/@ethersproject/abi/lib/coders/number.js:49:28)\n    at /app/node_modules/@ethersproject/abi/lib/coders/array.js:80:27\n    at Array.forEach (<anonymous>)\n    at Object.unpack (/app/node_modules/@ethersproject/abi/lib/coders/array.js:71:12)\n    at TupleCoder.decode (/app/node_modules/@ethersproject/abi/lib/coders/tuple.js:39:49)","level":"error","message":"Error initializing the server : data out-of-bounds (length=0, offset=32, version=abi/5.0.0-beta.138)"}
incubed-server_1  | {"reason":{},"promise":{},"level":"error","message":"Unhandled promise rejection at [object Promise]"}

```

**Comment by junaidev** [comment]
if parity is not sync then this happens, so a user can do ```docker-compose up incubed-parity``` until its sync and then ```docker-compose up``` or alternatively for quick evaluation of in3 server in new version of https://in3-setup.slock.it/ you can specify already synced parity url in wizard.

**Comment by ligi** [comment]
@junaidev thanks for the clarification and the workaround. Still leaving this open as I think this "unsynced" state could be handled by in3 for less friction/confusion of new users

**Comment by junaidev** [comment]
Thanks for suggestion, we are working on this. IN3 server will inform user if parity is not sync.

**Comment by junaidev** [comment]
fixed, now in3 server will show message.
